version: '3.9'

services:
  server:
    build: .
    ports:
      - '3000:3000'
  database:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: 'blog1996'
      POSTGRES_USER: 'blog'
      JWT_KEY: 'blog1996'
    volumes:
      - data:/var/lib/postgresql/data


volumes:
  data: